# Tributary configuration
# https://github.com/tributary/tributary

platforms:
  github:
    type: github
    url: https://api.github.com
    token_env: GITHUB_TOKEN
repositories:
- platform: github
  repo: jensens/ivoryvalley
active_repo: jensens/ivoryvalley
workflow:
  labels:
    ready: status/agent-ready
    in_progress: status/in-progress
    blocked: status/blocked
    epic: type/epic
